spring.application.name=auth-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wali-auth-service-db
spring.datasource.username=wali-auth-service-db-user
spring.datasource.password=w4xy8jW#JKJw=L@2
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#jwt
app.jwt.secret=7odqy66g3gr4j4rvodmuuuvavnlksfm6ie2y58rvni6hi197r3m547m3375fml6n

# kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=auth-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer