services:
  postgres:
    image: postgres:latest
    container_name: wali-notification-service-postgres
    restart: always
    environment:
      POSTGRES_USER: wali-notification-service-db-user
      POSTGRES_PASSWORD: NVVRw-G9hHSXHAFB
      POSTGRES_DB: wali-notification-service-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data+
volumes:
  postgres_data:
    driver: local