apiVersion: v1
kind: Service
metadata:
  name: wali-notification-service-db
  labels:
    app: wali-notification-service-db
spec:
  clusterIP: None # chaque pod a une ip seul alors que sans cluster ip il y'a une adresse seul (utulil pour les statefulset comme les db) pour tout les pods de mmaniere dynamique
  selector:
    app: wali-notification-service-db
  ports:
      - port: 5432
        targetPort: 5432