apiVersion: v1
kind: Service
metadata:
  name: wali-wallet-service-db
  labels:
    app: wali-wallet-service-db
spec:
  clusterIP: None
  selector:
    app: wali-wallet-service-db
  ports:
      port: 5432
      targetPort: 5432