services:
  postgres:
    image: postgres:latest
    container_name: wali-auth-service-postgres
    restart: always
    environment:
      POSTGRES_USER: wali-auth-service-db-user
      POSTGRES_PASSWORD: w4xy8jW#JKJw=L@2
      POSTGRES_DB: wali-auth-service-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data+
volumes:
  postgres_data:
    driver: local